// Copyright (c) 2026, the R8 project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

package com.android.tools.r8.dex;

import com.android.tools.r8.ClassFileResourceProvider;
import com.android.tools.r8.DiagnosticsHandler;
import com.android.tools.r8.ProgramResource;
import com.android.tools.r8.ProgramResource.Kind;
import com.android.tools.r8.origin.Origin;
import com.google.common.collect.ImmutableSet;
import java.io.IOException;
import java.util.Base64;
import java.util.Set;
import java.util.function.Consumer;

public class SunMiscUnsafeResourceProvider {

  private static final byte[] UNSAFE_CLASS_BYTES = sunMiscUnsafeBytes();

  public static ClassFileResourceProvider create() {
    return new ClassFileResourceProvider() {

      @Override
      public Set<String> getClassDescriptors() {
        return ImmutableSet.of("Lsun/misc/Unsafe;");
      }

      @Override
      public ProgramResource getProgramResource(String descriptor) {
        if (!descriptor.equals("Lsun/misc/Unsafe;")) {
          return null;
        }
        return ProgramResource.fromBytes(
            Origin.unknown(), Kind.CF, UNSAFE_CLASS_BYTES, getClassDescriptors());
      }

      @Override
      public void getProgramResources(Consumer<ProgramResource> consumer) {
        consumer.accept(
            ProgramResource.fromBytes(
                Origin.unknown(), Kind.CF, UNSAFE_CLASS_BYTES, getClassDescriptors()));
      }

      @Override
      public void finished(DiagnosticsHandler handler) throws IOException {
        ClassFileResourceProvider.super.finished(handler);
      }
    };
  }

  public static byte[] sunMiscUnsafeBytes() {
    // Atomically created by GenerateSunMiscUnsafe.
    return Base64.getDecoder()
        .decode(
            "yv66vgAAADQAcgEAD3N1bi9taXNjL1Vuc2FmZQcAAQEAEGphdmEvbGFuZy9PYmplY3QHAAMBABRJTlZBTElEX0ZJRUxEX09GRlNFVAEAAUkDAAAAAAEAC2FkZHJlc3NTaXplAQADKClJAQAQYWxsb2NhdGVJbnN0YW5jZQEAJShMamF2YS9sYW5nL0NsYXNzOylMamF2YS9sYW5nL09iamVjdDsBAA5hbGxvY2F0ZU1lbW9yeQEABChKKUoBAA9hcnJheUJhc2VPZmZzZXQBABQoTGphdmEvbGFuZy9DbGFzczspSQEAD2FycmF5SW5kZXhTY2FsZQEAEWNvbXBhcmVBbmRTd2FwSW50AQAYKExqYXZhL2xhbmcvT2JqZWN0O0pJSSlaAQASY29tcGFyZUFuZFN3YXBMb25nAQAYKExqYXZhL2xhbmcvT2JqZWN0O0pKSilaAQAUY29tcGFyZUFuZFN3YXBPYmplY3QBADooTGphdmEvbGFuZy9PYmplY3Q7SkxqYXZhL2xhbmcvT2JqZWN0O0xqYXZhL2xhbmcvT2JqZWN0OylaAQAKY29weU1lbW9yeQEABihKSkopVgEAHGNvcHlNZW1vcnlGcm9tUHJpbWl0aXZlQXJyYXkBABgoTGphdmEvbGFuZy9PYmplY3Q7SkpKKVYBABpjb3B5TWVtb3J5VG9QcmltaXRpdmVBcnJheQEAGChKTGphdmEvbGFuZy9PYmplY3Q7SkopVgEACmZyZWVNZW1vcnkBAAQoSilWAQAJZnVsbEZlbmNlAQADKClWAQAMZ2V0QW5kQWRkSW50AQAXKExqYXZhL2xhbmcvT2JqZWN0O0pJKUkBAA1nZXRBbmRBZGRMb25nAQAXKExqYXZhL2xhbmcvT2JqZWN0O0pKKUoBAAxnZXRBbmRTZXRJbnQBAA1nZXRBbmRTZXRMb25nAQAPZ2V0QW5kU2V0T2JqZWN0AQA5KExqYXZhL2xhbmcvT2JqZWN0O0pMamF2YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9PYmplY3Q7AQAKZ2V0Qm9vbGVhbgEAFihMamF2YS9sYW5nL09iamVjdDtKKVoBAAdnZXRCeXRlAQAWKExqYXZhL2xhbmcvT2JqZWN0O0opQgEABChKKUIBAAdnZXRDaGFyAQAWKExqYXZhL2xhbmcvT2JqZWN0O0opQwEABChKKUMBAAlnZXREb3VibGUBABYoTGphdmEvbGFuZy9PYmplY3Q7SilEAQAEKEopRAEACGdldEZsb2F0AQAWKExqYXZhL2xhbmcvT2JqZWN0O0opRgEABChKKUYBAAZnZXRJbnQBABYoTGphdmEvbGFuZy9PYmplY3Q7SilJAQAEKEopSQEADmdldEludFZvbGF0aWxlAQAHZ2V0TG9uZwEAFihMamF2YS9sYW5nL09iamVjdDtKKUoBAA9nZXRMb25nVm9sYXRpbGUBAAlnZXRPYmplY3QBACcoTGphdmEvbGFuZy9PYmplY3Q7SilMamF2YS9sYW5nL09iamVjdDsBABFnZXRPYmplY3RWb2xhdGlsZQEACGdldFNob3J0AQAWKExqYXZhL2xhbmcvT2JqZWN0O0opUwEABChKKVMBAAlnZXRVbnNhZmUBABMoKUxzdW4vbWlzYy9VbnNhZmU7AQAJbG9hZEZlbmNlAQARb2JqZWN0RmllbGRPZmZzZXQBABwoTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOylKAQAIcGFnZVNpemUBAARwYXJrAQAFKFpKKVYBAApwdXRCb29sZWFuAQAXKExqYXZhL2xhbmcvT2JqZWN0O0paKVYBAAdwdXRCeXRlAQAXKExqYXZhL2xhbmcvT2JqZWN0O0pCKVYBAAUoSkIpVgEAB3B1dENoYXIBABcoTGphdmEvbGFuZy9PYmplY3Q7SkMpVgEABShKQylWAQAJcHV0RG91YmxlAQAXKExqYXZhL2xhbmcvT2JqZWN0O0pEKVYBAAUoSkQpVgEACHB1dEZsb2F0AQAXKExqYXZhL2xhbmcvT2JqZWN0O0pGKVYBAAUoSkYpVgEABnB1dEludAEAFyhMamF2YS9sYW5nL09iamVjdDtKSSlWAQAFKEpJKVYBAA5wdXRJbnRWb2xhdGlsZQEAB3B1dExvbmcBABcoTGphdmEvbGFuZy9PYmplY3Q7SkopVgEABShKSilWAQAPcHV0TG9uZ1ZvbGF0aWxlAQAJcHV0T2JqZWN0AQAoKExqYXZhL2xhbmcvT2JqZWN0O0pMamF2YS9sYW5nL09iamVjdDspVgEAEXB1dE9iamVjdFZvbGF0aWxlAQANcHV0T3JkZXJlZEludAEADnB1dE9yZGVyZWRMb25nAQAQcHV0T3JkZXJlZE9iamVjdAEACHB1dFNob3J0AQAXKExqYXZhL2xhbmcvT2JqZWN0O0pTKVYBAAUoSlMpVgEACXNldE1lbW9yeQEABihKSkIpVgEACnN0b3JlRmVuY2UBAAZ1bnBhcmsBABUoTGphdmEvbGFuZy9PYmplY3Q7KVYBAA1Db25zdGFudFZhbHVlAQAEQ29kZQARAAIABAAAAAEAGQAFAAYAAQBwAAAAAgAHAEMBAQAIAAkAAAEBAAoACwAAAQEADAANAAAAAQAOAA8AAQBxAAAADgAAAAAAAAACA6wAAAAAAAEAEAAPAAEAcQAAAA4AAAAAAAAAAgOsAAAAAAEBABEAEgAAAQEAEwAUAAABAQAVABYAAAEBABcAGAAAAQEAGQAaAAABAQAbABwAAAEBAB0AHgAAAQEAHwAgAAAAEQAhACIAAQBxAAAADgAAAAAAAAACA6wAAAAAABEAIwAkAAEAcQAAAA4AAAAAAAAAAgmtAAAAAAARACUAIgABAHEAAAAOAAAAAAAAAAIDrAAAAAAAEQAmACQAAQBxAAAADgAAAAAAAAACCa0AAAAAABEAJwAoAAEAcQAAAA4AAAAAAAAAAgGwAAAAAAEBACkAKgAAAQEAKwAsAAABAQArAC0AAAEBAC4ALwAAAQEALgAwAAABAQAxADIAAAEBADEAMwAAAQEANAA1AAABAQA0ADYAAAEBADcAOAAAAQEANwA5AAABAQA6ADgAAAEBADsAPAAAAQEAOwANAAABAQA9ADwAAAEBAD4APwAAAQEAQAA/AAABAQBBAEIAAAEBAEEAQwAAAAkARABFAAEAcQAAAA4AAAAAAAAAAgGwAAAAAAEBAEYAIAAAAAEARwBIAAEAcQAAAA4AAAAAAAAAAgmtAAAAAAEBAEkACQAAAQEASgBLAAABAQBMAE0AAAEBAE4ATwAAAQEATgBQAAABAQBRAFIAAAEBAFEAUwAAAQEAVABVAAABAQBUAFYAAAEBAFcAWAAAAQEAVwBZAAABAQBaAFsAAAEBAFoAXAAAAQEAXQBbAAABAQBeAF8AAAEBAF4AYAAAAQEAYQBfAAABAQBiAGMAAAEBAGQAYwAAAQEAZQBbAAABAQBmAF8AAAEBAGcAYwAAAQEAaABpAAABAQBoAGoAAAEBAGsAbAAAAQEAbQAgAAABAQBuAG8AAAAA");
  }
}
